# Generated by Django 2.2.7 on 2019-11-27 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_number', models.CharField(max_length=10)),
                ('phone_number', models.IntegerField()),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('days_of_leave', models.IntegerField()),
                ('status', models.CharField(choices=[('new', 'New'), ('app', 'Approved'), ('decl', 'Declined')], default='new', max_length=10)),
                ('employee_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LeaveLogger.Employee')),
            ],
        ),
    ]
